# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Firebase distribution lane"
  lane :firebase_distribution do |options|
    begin
      # Define varaibles
      flavor = options[:flavor] || "development"
      target = "lib/main/main_#{flavor}.dart"
      app_bundle_path = "../build/app/outputs/flutter-apk/app-#{flavor}-release.apk"
      # Build Apk
      sh "flutter clean"
      sh "flutter pub get"
      sh "cd ../../ && dart run build_runner build --delete-conflicting-outputs"
      sh "flutter analyze"
      sh "flutter build apk --release --flavor #{flavor} --target #{target}"

      # Upload to Firebase
      firebase_app_distribution(
        app: "1:283100953486:android:f8f9aaa1a92e0d9293c2df",
        firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"],
        groups: "internal-testers",
        release_notes: "New version",
        android_artifact_type: "APK",
        android_artifact_path: app_bundle_path,
      )
    end
  end
end
