name: "Android Fastlane Firebase app distribution workflow"

on: 
    push:
        branches:
            - master
            - main
    pull_request:
        branches:
            - master
            - main

jobs: 
    distribute_to_firebase:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout my repo update
          uses: actions/checkout@v2
      
        - name: Setup JDK 17
          uses: actions/setup-java@v2
          with:
            java-version: '17'
            distribution: 'temurin'

        - name: Install Flutter
          uses: subosito/flutter-action@v2
          with:
            channel: stable
        - run: flutter --version

        - name: Setup Ruby
          uses: ruby/setup-ruby@v1
          with:
            ruby-version: "3.2.3"
            bundler-cache: true
            working-directory: android

        - name: Build and Distribute App
          env:
                FIREBASE_CLI_TOKEN: ${{ secrets.FIREBASE_CLI_TOKEN }}
                FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID_DEV }}
          run: |
                bundle exec fastlane android firebase_distribution flavor:development
          working-directory: android
